name: Lint, Test, and Package

on: [ pull_request ]

env:
  PANTS_CONFIG_FILES: pants.ci.toml

jobs:
  source:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Configure Pants caching to GitHub Actions Cache
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('PANTS_REMOTE_STORE_ADDRESS', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('PANTS_REMOTE_OAUTH_BEARER_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
    - name: Pants Lint
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
        pants lint all
    - name: Pants Test
      run: pants test all
    - name: Pants Package
      run: pants package all
